on:
  push:
    branches: ["main"]

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./new
      - id: deployment
        uses: actions/deploy-pages@v3
